################################################################
# Travis CI Configuration file for Embedded Reflex Test
# Created by Luke Hsiao & Travis Chambers
# 28 May 2015
################################################################
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
install:
  - bundle install ceedling
script:
  - rake test:all
  
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eab4e551d60a98013fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
