################################################################
# Travis CI Configuration file for Embedded Reflex Test
# Created by Luke Hsiao & Travis Chambers
# 28 May 2015
################################################################
language: c
compiler:
  - gcc
#  - clang

# Run Unit Tests
# script: cd tests && make
  
notifications:
  email: false  
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eab4e551d60a98013fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
